ProductManagementSLN/ProductManagement/Controllers/ProductController.cs
using ProductManagement.Models;
using ProductManagement.Models.ViewModels;
using ProductManagement.Repository;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductManagement.Controllers
{

    public class ProductController : Controller
    {
        ProductRepository repo=new ProductRepository();
        [Authorize(Roles ="View, Admin")]
        public ActionResult Index()
        {
            IEnumerable<ProductViewModel> list = repo.GetAllProduct();
            return View(list);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            List<Supplier> list=repo.GetSuppliers();
            ViewBag.Suppliers=list;
            return View();
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            List<Supplier> list = repo.GetSuppliers();
            ViewBag.Suppliers = list;
            Product vObj = repo.GetProductById(id);
            ProductViewModel obj=new ProductViewModel();
            obj.ProductName = vObj.ProductName;
            obj.PurchaseDate = vObj.PurchaseDate;
            obj.Quantity = vObj.Quantity;
            obj.UnitPrice = vObj.UnitPrice;
            obj.SupplierId = vObj.SupplierId;
            obj.EmailAddress = vObj.EmailAddress;
            obj.ImageName = vObj.ImageName;
            obj.ImageUrl = vObj.ImageUrl;
            obj.ProductId = vObj.ProductId;
            return View(obj);
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(ProductViewModel vObj)
        {
            bool result = false;
            Product obj;
            if (vObj.ProductId == 0)
            {
                if (ModelState.IsValid)
                {
                    obj = new Product();
                    obj.ProductName = vObj.ProductName;
                    obj.PurchaseDate = vObj.PurchaseDate;
                    obj.Quantity = vObj.Quantity;
                    obj.UnitPrice = vObj.UnitPrice;
                    obj.SupplierId = vObj.SupplierId;
                    obj.EmailAddress = vObj.EmailAddress;
                    string fileName = Path.GetFileNameWithoutExtension(vObj.ImageFile.FileName);
                    string extension = Path.GetExtension(vObj.ImageFile.FileName);
                    fileName = fileName + extension;
                    obj.ImageName = fileName;
                    obj.ImageUrl = "~/Images/" + obj.ImageName;
                    fileName = Path.Combine(Server.MapPath(obj.ImageUrl));
                    vObj.ImageFile.SaveAs(fileName);
                    repo.SaveProduct(obj);
                    result = true;
                }
            }
            else
            {
                obj=repo.GetProductById(vObj.ProductId);
                obj.ProductName = vObj.ProductName;
                obj.PurchaseDate = vObj.PurchaseDate;
                obj.Quantity = vObj.Quantity;
                obj.UnitPrice = vObj.UnitPrice;
                obj.SupplierId = vObj.SupplierId;
                obj.EmailAddress = vObj.EmailAddress;
                obj.ProductId = vObj.ProductId;
                if (vObj.ImageFile != null)
                {
                    DeleteExistingImage(obj.ImageName);
                    string fileName = Path.GetFileNameWithoutExtension(vObj.ImageFile.FileName);
                    string extension = Path.GetExtension(vObj.ImageFile.FileName);
                    fileName = fileName + extension;
                    obj.ImageName = fileName;
                    obj.ImageUrl = "~/Images/" + obj.ImageName;
                    fileName = Path.Combine(Server.MapPath(obj.ImageUrl));
                    vObj.ImageFile.SaveAs(fileName);
                }
                else
                {
                    obj.ImageName=obj.ImageName;
                    obj.ImageUrl=obj.ImageUrl;
                }
                repo.UpdateProduct(obj);
                result = true;
            }
            if(result)
            {
                return RedirectToAction("Index");
            }
            else
            {
                List<Supplier> suppliers = repo.GetSuppliers();
                ViewBag.Suppliers = suppliers;
                return View();
            }          
           
        }
        public ActionResult Delete(int id)
        {
            List<Supplier> list = repo.GetSuppliers();
            ViewBag.Suppliers = list;
            Product vObj = repo.GetProductById(id);
            ProductViewModel obj = new ProductViewModel();
            obj.ProductName = vObj.ProductName;
            obj.PurchaseDate = vObj.PurchaseDate;
            obj.Quantity = vObj.Quantity;
            obj.UnitPrice = vObj.UnitPrice;
            obj.SupplierId = vObj.SupplierId;
            obj.EmailAddress = vObj.EmailAddress;
            obj.ImageName = vObj.ImageName;
            obj.ImageUrl = vObj.ImageUrl;
            obj.ProductId = vObj.ProductId;
            return View(obj);
        }
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirm(ProductViewModel vObj)
        {
            bool result=false;
            Product obj=repo.GetProductById(vObj.ProductId);
            string imageName = vObj.ImageName;
            DeleteExistingImage(imageName);
            try
            {
                repo.DeleteProduct(obj.ProductId);
                result = true;
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                result = false;
                return View(vObj);
            }           

           
        }
        public PartialViewResult Details(int id)
        {
            List<Supplier> list = repo.GetSuppliers();
            ViewBag.Suppliers = list;
            Product vObj = repo.GetProductById(id);
            ProductViewModel obj = new ProductViewModel();
            obj.ProductName = vObj.ProductName;
            obj.PurchaseDate = vObj.PurchaseDate;
            obj.Quantity = vObj.Quantity;
            obj.UnitPrice = vObj.UnitPrice;
            obj.SupplierId = vObj.SupplierId;
            obj.EmailAddress = vObj.EmailAddress;
            obj.ImageName = vObj.ImageName;
            obj.ImageUrl = vObj.ImageUrl;
            obj.ProductId = vObj.ProductId;
            ViewBag.Details = "Show";
            return PartialView("_DetailsRecord", obj);
        }
        private void DeleteExistingImage(string imageName)
        {
            string root=Server.MapPath("~");
            string parent=Path.GetDirectoryName(root);
            string path = parent + "/Images/" + imageName;
            FileInfo fileObj= new FileInfo(path);
            if (fileObj.Exists)
            {
                fileObj.Delete();
            }
        }
    }
}

ProductManagementSLN/ProductManagement/Controllers/SupplierController.cs
using ProductManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductManagement.Controllers
{
    public class SupplierController : Controller
    {
        ProductManagemenrDBEntities db = new ProductManagemenrDBEntities();
        public ActionResult Index()
        {
            List<Supplier> suppliers = db.Suppliers.ToList();
            return View(suppliers);
        }
        public ActionResult CreateSupplier()
        {
            return View();
        }
        public ActionResult AjaxCreateSupplier(Supplier obj) 
        { 
            if(ModelState.IsValid)
            {
                System.Threading.Thread.Sleep(5000);
                db.Suppliers.Add(obj);
                db.SaveChanges();
            }
            IEnumerable<Supplier> Model = db.Suppliers.ToList();
            return PartialView("_SupplierDetails", Model);
        }
    }
}

ProductManagementSLN/ProductManagement/Views/Shared/_DetailsRecord.cshtml
@model ProductManagement.Models.ViewModels.ProductViewModel
<div class="col-md-5 mx-auto my-5">
    <h2>Details Product</h2>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "form-label" })
        @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

    </div>
    <div class="form-group mb-3 position-relative">
        @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "form-label" })
        @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control datetimepicker", @disabled = "disabled" } })

    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.SupplierId, htmlAttributes: new { @class = "form-label" })

        @Html.DropDownListFor(model => model.SupplierId, new SelectList(ViewBag.Suppliers, "SupplierId", "SupplierName"), "Select Supplier", new { @class = "form-select", @disabled = "disabled" })

    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "form-label" })

        @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })

    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "form-label" })

        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "form-label" })

        @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

    </div>
    <div class="form-group mb-3">
        @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "form-label  mb-3" })<br />
        <img src="@Url.Content(Model.ImageUrl)" alt="@Model.ImageName" height="120" width="110" class="changeEdit" />
    </div>  

   
</div>

ProductManagementSLN/ProductManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-datetimepicker.css" rel="stylesheet" />
    @RenderSection("head", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Product Management</a>
            <button class="navbar-toggler" type="button" data-bs-toggler="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar nav me-auto mb-2 mb-lg-0">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
                        {
                            @*<li class="nav-item">
                                @Html.ActionLink("User Role Edit", "Index", "Admin", new { area = "" }, new { @class = "nav-link active" })
                            </li>*@

                            <li class="nav-item">
                                @Html.ActionLink("Create And Edit Role", "CreateRole", "Admin", new { area = "" }, new { @class = "nav-link active" })
                            </li>
                        }
                        <li class="nav-item">
                            @Html.ActionLink("Home", "Index", "Product", new { area = "" }, new { @class = "nav-link active" })
                        </li>

                        <li class="nav-item">
                            @Html.ActionLink("Create Product", "Create", "Product", new { area = "" }, new { @class = "nav-link active" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Create Supplier", "Index", "Supplier", new { area = "" }, new { @class = "nav-link active" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Hello"+User.Identity.Name,"", new { area = "" }, new { @class = "nav-link active" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Logout", "lgout", "Account", new { area = "" }, new { @class = "nav-link active" })
                        </li>
                    }
                    else   
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "nav-link active" })
                        </li>

                    }

                </ul>
                <form class="d-flex">
                    @using (Html.BeginForm("Index", "Products", FormMethod.Get))
                    {
                        @Html.TextBox("SearchString", null, htmlAttributes: new { @class = "form-control me-2", @type = "search", @placeholer = "Search" })
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    }

                </form>
            </div>
        </div>
    </nav>
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center"> &copy; @DateTime.Now.Year - Product Management &reg;</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.js"></script>
    <script src="~/Scripts/custom.js"></script>
</body>
</html>

ProductManagementSLN/ProductManagement/Views/Shared/_SupplierDetails.cshtml
@model IEnumerable<ProductManagement.Models.Supplier>
@{
        //Layout = "~/Views/Shared/_Layout.cshtml";
    }
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<h3>Supplier List</h3>
<div>
    <table class="table table-bordered table-striped">
        <tr>
            <th colspan="2"><h5>Page Loading @@: @DateTime.Now.ToString()</h5></th>
        </tr>
        <tr>
            <th>Supplier Id</th>
            <th>Supplier Name</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.SupplierId</td>
                <td>@item.SupplierName</td>
            </tr>
        }
    </table>
</div>